### ISSUE TITLE
"search_type" -> "scan" is no longer supported

### ISSUE THREAD

**Issue by agearhart** [SumoLogic/elasticsearch-client#100]
Attempting to run a startScrollRequest against an AWS Elasticsearch 5.1 instance results in an exception with the message

org.json4s.package$MappingException: No usable value for error
Do not know how to convert JObject(List((root_cause,JArray(List(JObject(List((type,JString(illegal_argument_exception)), (reason,JString(No search type for [scan]))))))), (type,JString(illegal_argument_exception)), (reason,JString(No search type for [scan])))) into class java.lang.String

**Comment by CCheSumo** [comment]
search_type=scan and search_type=count are deprecated in Elasticsearch 2.1. A relative thread https://github.com/elastic/elasticsearch-net/issues/1745 is here.

**Comment by CCheSumo** [comment]
Both `search_type=scan` and `search_type=count` has been deprecated.

Document https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_21_search_changes.html

**Comment by CCheSumo** [comment]
https://github.com/SumoLogic/elasticsearch-client/pull/121

**Comment by agearhart** [comment]
Thanks!  I meant to close this after your first reply, sorry.
