### ISSUE TITLE
QueryDsl QueryRoot.toJson incorrect for sort

### ISSUE THREAD

**Issue by mvaal** [SumoLogic/elasticsearch-client#101]
Hello,
There appears to be a bug in your API.  When giving multiple field sorts, only the last one is taken.
After debugging the issue, we found the issue in QueryDsl QueryRoot.toJson:
`
override def toJson: Map[String, Any] = {
      Map(_query -> query.toJson) ++
        fromOpt.map(_from -> _) ++
        sizeOpt.map(_size -> _) ++
        timeout.map(t => _timeout -> s"${t}ms") ++
        sort.map(_sort -> _.toJson) ++
        sourceFilter.map(_source -> _)
    }
`
The sort is a Seq[Sort] rather than an Option[Seq[Sort]], so the mapping is overwriting the key when we give multiple values.

At a glance, this could be resolved by making the primary constructor of QueryRoot accept an Option[Seq[Sort]] instead of converting in the apply method.

**Comment by rcoh** [comment]
Thanks will take a look. Would also accept test+PR.

**Comment by mvaal** [comment]
Created PR#102.
https://github.com/SumoLogic/elasticsearch-client/pull/102
Thanks.
