### ISSUE TITLE
runRawEsRequest DELETE on a document throws an org.json4s.MappingException

### ISSUE THREAD

**Issue by agearhart** [SumoLogic/elasticsearch-client#106]
The actual DELETE request on an /index/type/id succeeds, however the creation of the RawJsonResponse throws the mapping exception.

noException should be thrownBy(  Await.result(restClient.runRawEsRequest(op = "", endpoint = "/testIndex/testType/bloopId", DELETE), Duration.Inf))

**Comment by CCheSumo** [comment]
@pnzrdrgoon I saw you created two PRs for supporting delete individual document deletes and bulk deletes by document id/ids. Is this still an issue for you?

**Comment by agearhart** [comment]
To be honest what I care most about is supporting bulkDelete.  Enabling
individual deletes would be nice, but not necessary at the moment.  I'll
address the feedback from bulkDelete ASAP and leave individual deletes for
later.

**Comment by agearhart** [comment]
This may now be closed in lieu of using deleteById now instead.
