### ISSUE TITLE
Please create an OperationType for Delete to support bulk deletes

### ISSUE THREAD

**Issue by agearhart** [SumoLogic/elasticsearch-client#107]
It would be very useful.

case object delete extends OperationType {
    override val jsonStr: String = "delete"
  }

**Comment by rcoh** [comment]
Will add it but won't have time until next week. Happy to accept a PR.

**Comment by agearhart** [comment]
I tried this past weekend, but Maven wouldn't run the tests because it couldn't find src/etc/header.txt.  Any ideas on what I did wrong?

**Comment by rcoh** [comment]
Yep, you need to run the tests from the root directory.

**Comment by rcoh** [comment]
If you can't get it to work, feel free to submit a PR anyway. The tests will get run on CI.

**Comment by agearhart** [comment]
Support for this has been merged.  Thank you all!
