### ISSUE TITLE
RestlasticSearchClient disconnect method

### ISSUE THREAD

**Issue by ZakariaHili** [SumoLogic/elasticsearch-client#154]
Hi,
Is that there is a method to stop the connection from RestlasticSearchClient to Elasticsearch server?

thank you in advance

**Comment by rcoh** [comment]
The RestlasticSearchClient is making individual GET and POST requests -- it doesn't keep a persistent connection to the server

**Comment by ZakariaHili** [comment]
I see, I thought that this client creates some kind of a pool connection,
 thank you.
