### ISSUE TITLE
Invalid security token in AWS request

### ISSUE THREAD

**Issue by ben-barnes** [SumoLogic/elasticsearch-client#19]
I am creating a request in the following manner:

```
// Client creation function:
def createClient(hostAddress: String): RestlasticSearchClient = {
  val credentialsProvider = new DefaultAWSCredentialsProviderChain()
  val awsCredentials = credentialsProvider.getCredentials

  val signer = new AwsRequestSigner(awsCredentials, "us-west-2", "es")
  val endpoint = new StaticEndpoint(new Endpoint(hostAddress, 443))
  new RestlasticSearchClient(endpoint, Some(signer))
}

val client = createClient("our-es-endpoint-12345-etc.us-west-2.es.amazonaws.com")
val response = client.count(index, tpe, query)
```

When I execute the `count` query, I get an HTTP 403 response with the following message: 

```
{"message":"The security token included in the request is invalid."}
```

I have a similar chunk of code running in Python, using the exact same credentials, endpoint and port, and it can access the Elasticsearch cluster without issue. It is using `requests_aws4auth`. Is there something I've missed? It seems there is a difference between how `elasticsearch-aws` and `requests_aws4auth` are forming the HTTP headers.

**Comment by rcoh** [comment]
Are you sure that your credentials provider is actually providing the creds? That error indicates that the request was signed properly but that the token was bogus (or missing).

[This issue](https://github.com/awslabs/amazon-kinesis-scaling-utils/issues/5) seems similar.

**Comment by ben-barnes** [comment]
Thanks for the quick reply. Yep, I printed out the access key ID and secret key from `awsCredentials`, they were both populated with the expected values. I'm going to try and dump complete HTTP requests from both the python and scala code, and see if there are any obvious differences.

**Comment by ben-barnes** [comment]
I should have mentioned I'm running this code inside AWS Lambda. Not sure if related, but it seems the issue is to do with another HTTP header, `x-amz-security-token`. The python code is populating that header from an environment variable, `AWS_SECURITY_TOKEN`. If I remove the header from the python code I get a similar 403 error.

I'm going to look into attaching this header to the HTTP request in `elasticsearch-client` and see if that fixes the problem.

**Comment by rcoh** [comment]
Ah cool -- you're almost certainly the first person to try to use this from
Lambda. We're using the `Authorization` header currently. You could try
adding the `x-amz-security-token` header to the list at
https://github.com/SumoLogic/elasticsearch-client/blob/master/elasticsearch-aws/src/main/scala/com/sumologic/elasticsearch/util/AwsRequestSigner.scala#L49
to
see if that does the trick.

**Comment by ben-barnes** [comment]
It worked! I added the following function to `AwsRequestSigner`:

```
val xAmzSecurityToken = "X-Amz-Security-Token"
private def addAmzToken(httpRequest: HttpRequest): HttpRequest = {
  val amzToken = sys.env.get("AWS_SESSION_TOKEN")
  amzToken map (token => {
    httpRequest.withHeaders(RawHeader(xAmzSecurityToken, token) :: httpRequest.headers)
  }) getOrElse httpRequest
}
```

Then, in `AwsRequestSigner::withAuthHeader` I call it on `withDateAndHost`:
`val withAmzToken = addAmzToken(withDateAndHost)`

This works in my case, but I don't know how useful it would be in general. Would you be interested in a pull request? It's also a little hard to unit test as-is, since the function requires environment variables to be set.

**Comment by rcoh** [comment]
Hmm. For a PR we'd need to remove the environment variable dep. I'll think
about it -- I'd like it to work out of the box for your use case.

**Comment by ben-barnes** [comment]
Alright, no worries. I'll close this issue then.

**Comment by rcoh** [comment]
Did a bit of research --

I think the best way to do this would be to pass in an `AWSSessionCredentials` (subclass of AWSCredentials) into the constructor.

In the request signer, match on the credentials object to see if it is actually AWSSessionCredentials, and if so send the session token.

I believe the credentials you're sending are already AWSSessionCredentials so the only change would need to be library side.

We'd certainly accept a PR for this if you'd like to code it 👍

**Comment by ben-barnes** [comment]
Ah, neat! Thanks for looking into that. I'll give it a go, though I may not be able to spend much time on it for the next few days.

**Comment by dr4ke616** [comment]
Hey guys, im actually getting the same issue as @chronon-io, difference being I'm running the application from a normal EC2 instance. 

Ive a code setup as follows:

``` scala
val credentialsProviderChain = new DefaultAWSCredentialsProviderChain()
val region = Option(Regions.getCurrentRegion).getOrElse(Region.getRegion(Regions.EU_WEST_1))
val signer = Some(new ExperimentalAwsRequestSigner(credentialsProviderChain.getCredentials, region.getName, "es"))

new RestlasticSearchClient(new StaticEndpoint(Endpoint(host, port)), signer)
```

The response im getting back is as follows:

```
[debug] c.s.e.r.RestlasticSearchClient$ - Got Es response: 403 Forbidden
[warn] c.s.e.r.RestlasticSearchClient$ - Failure response: {"message":"The security token included in the request is invalid."}
[warn] c.s.e.r.RestlasticSearchClient$ - Failing request: {"query":{"term":{"_id":"a1195665-53b6-4e97-bde6-e7b918e92525"}}}
```

**Comment by rcoh** [comment]
What is the `ExperimentalAwsRequestSigner`? By the way, https://github.com/SumoLogic/elasticsearch-client/issues/55 reported that he upgraded to 1.0.24 and it worked.
