### ISSUE TITLE
Missing nested query DSL support

### ISSUE THREAD

**Issue by ArnaudT** [SumoLogic/elasticsearch-client#56]
Hi,

We start to use your library (we were using an internal library) for the elasticsearch 2.3 and AWS support. We are really happy so far! 👍 

I didn't find any DSL to create nested queries (Nested query allows to query nested objects / docs).
More information is available on the [elasticsearch doc](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-nested-query.html).

I will create in few minutes a pull request for the `NestedQuery` support.
Please, tell me what you think!

I'll create more issues / PR for missing functionalities that we need in the following days if you are interested.

Thanks! 
Arnaud.

**Comment by rcoh** [comment]
Please do! And no need to create issues if you don't want to, we'll gladly accept just PRs

**Comment by ArnaudT** [comment]
Great! I'll create just PRs from now. Thanks.
