### ISSUE TITLE
Expired credentials provider

### ISSUE THREAD

**Issue by ArnaudT** [SumoLogic/elasticsearch-client#63]
Hi,

We have an issue with the AWS credentials.

We are instantiating the service like in the README.md:

```
  private val signer = new AwsRequestSigner(awsCredentials, "us-east-1", "es")
  private val endpoint = new StaticEndpoint(Endpoint(elasticSearch.getHost, elasticSearch.getPort))
  private val restClient = new RestlasticSearchClient(endpoint, Some(signer))
```

We are using the credentials provider implementation that loads credentials from the Amazon EC2 Instance Metadata Service named `InstanceProfileCredentialsProvider`.
After few hours we have the following error message:

`{"message":"The security token included in the request is expired"}`

We should refresh the temporary credentials but it seems it's not possible with the current implementation of the client.

Do you have any advices about handling expiring tokens? 

One option could be to instantiate a new instance of `RestlasticSearchClient` at each request but this will instantiate a new `ActorSystem()` each time. Which is a really heavy operation. 
Furthermore, I do not think instantiating an actor system in the client is a good thing. As the akka doc says: [An ActorSystem is a heavyweight structure that will allocate 1…N Threads, so create one per logical application.](http://doc.akka.io/docs/akka/2.4/general/actor-systems.html)
One improvement could be to remove the creation of the `ActorSystem` within this class and add it as a dependency as the `indexExecutionCtx: ExecutionContext` or `searchExecutionCtx: ExecutionContext`. So we can have only one `ActorSystem` per application.

What do you think?

Some resources:
- https://aws.amazon.com/premiumsupport/knowledge-center/security-token-expired/
- http://stackoverflow.com/questions/36732171/sqs-expiredtoken-the-security-token-included-in-the-request-is-expired-status-c

Thanks,
Arnaud.

**Comment by rcoh** [comment]
Fixed.
