### ISSUE TITLE
Add query boost

### ISSUE THREAD

**Issue by Cowa** [SumoLogic/elasticsearch-client#68]
Hi,
Thanks for this library, it works very well.

But there is one missing feature for my case that prevent me to fully adopt it: boosting query:
https://www.elastic.co/guide/en/elasticsearch/guide/current/_boosting_query_clauses.html

I don't know if it would be difficult to implement it.
I may open a PR if I manage to take some time!

**Comment by rcoh** [comment]
Looks like it would be pretty straightforward to add. 
https://github.com/SumoLogic/elasticsearch-client/blob/master/elasticsearch-core/src/main/scala/com/sumologic/elasticsearch/restlastic/dsl/QueryDsl.scala has the current query features, and it's easy to add new ones. Let me know if you have any questions.
