### ISSUE TITLE
Flaky Test

### ISSUE THREAD

**Issue by rcoh** [SumoLogic/elasticsearch-client#72]
"Be able to create an index and setup index setting with keyword lowercase analyzer"
https://travis-ci.org/SumoLogic/elasticsearch-client/builds/161348069

**Comment by claymccoy** [comment]
Here is another flaky one:
![screen shot 2016-12-16 at 10 00 55 pm](https://cloud.githubusercontent.com/assets/2743/21284711/cece8524-c3e9-11e6-980e-8a6b5e547688.png)

**Comment by CCheSumo** [comment]
https://github.com/SumoLogic/elasticsearch-client/pull/124

**Comment by CCheSumo** [comment]
This has been fixed here https://github.com/SumoLogic/elasticsearch-client/pull/124
