### ISSUE TITLE
Can't run raw request "/_cat/indices?bytes=m"

### ISSUE THREAD

**Issue by Cowa** [SumoLogic/elasticsearch-client#83]
Hello,

I'm doing a raw request to list indices. My code looks like this:

``` scala
client.runRawEsRequest("", "/_cat/indices?bytes=m", GET)
```

I get this warn log: `RestlasticSearchClient$ - Failure response: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No feature for name [indices?bytes=m]"}],"type":"illegal_argument_exception","reason":"No feature for name [indices?bytes=m]"},"status":400}`

It works when I'm using directly the ES endpoint (through Postman for example).

It seems it's the query parameter `?bytes=m` which causes the error. Because this request works perfectly:

``` scala
client.runRawEsRequest("", "/_cat/indices", GET)
```

**Comment by Cowa** [comment]
Ok I figured it out!

The last parameter of `runRawEsRequest` can take some `UriQuery`.
In my case I passed `Raw("bytes=m")` and everything works fine.

👍

**Comment by rcoh** [comment]
Nice catch, sorry about the confusion. Maybe we should add some kind of warning if people try to pass URL params in the URL...
