### ISSUE TITLE
RestlasticSearchClient ActorSystem creation by default causing issues

### ISSUE THREAD

**Issue by mvaal** [SumoLogic/elasticsearch-client#85]
We are running into an issue right now where we are only able to run a single RestlasticSearchClient on a machine because the ActorSystem being created is always default and we are unable to pass props. 
`implicit val system: ActorSystem = ActorSystem()`
Normally I would just override the val for this and set my own value, but unfortunately with how Scala works, it is still calling the initialization and creating the ActorSystem prior to my value being set (so 2 actor systems are created).
Is there a work around for this?

Otherwise please consider making it configurable.
Possible solutions:
Lazy Init:
`implicit lazy val system: ActorSystem = ActorSystem()`
or implicit parameter pass in:
`class RestlasticSearchClient(endpointProvider: EndpointProvider, signer: Option[RequestSigner] = None, indexExecutionCtx: ExecutionContext = ExecutionContext.Implicits.global, searchExecutionCtx: ExecutionContext = ExecutionContext.Implicits.global)(implicit val system: ActorSystem = ActorSystem()){}`

Thanks for your time.

**Comment by rcoh** [comment]
Sorry about that. I'll make a change to make it a parameter and push it
this evening. Would also accept a pull request.

**Comment by mvaal** [comment]
I have submitted a pull request.  Thanks for the quick response.

**Comment by rcoh** [comment]
@CCheSumo would you mind cutting a new release when you get a chance?

**Comment by CCheSumo** [comment]
@rcoh I will push a new release out today.

**Comment by mvaal** [comment]
Any updates on this?  Thanks.

**Comment by CCheSumo** [comment]
@SplashAttacks cutting the release now. It should be available in half an hour or so.

**Comment by CCheSumo** [comment]
@SplashAttacks release cut has been made. The new release version is 1.0.28. Cheers ~

**Comment by mvaal** [comment]
Looks good, thanks a bunch!
