### ISSUE TITLE
Update deps to ES5?

### ISSUE THREAD

**Issue by ecausarano** [SumoLogic/elasticsearch-client#89]

**Comment by rcoh** [comment]
I wouldn't be opposed to making a branch with ES5 support, but I don't think there are any current plans to support ES5 features.

**Comment by ecausarano** [comment]
Still... it's necessary for testing in a project that has other dependancies on Elastic 5

**Comment by CCheSumo** [comment]
We need to do a sequential upgrade as 1.x -> 2.x -> 5.x as the jump 1.x -> 5.x is not supported from either Elasticsearch or AWS.
- Migrate from 1.x to 5.x is not supported in Elasticsearch (Breaking Changes) and AWS [http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html]
- There were many breaking changes that requires api changes between 1.x to 5.x. It will be a big hurdle for users of the library to go from 1.x to 5.x.

Upgrading to 2.x is in progress and almost complete. I post a update here when it is released.

**Comment by hit436** [comment]
ES5/ES6 client support release tentative date? Any chances of releasing it this month?

**Comment by Ankurkkhurana** [comment]
There are currently no plans to make a switch to ES5 and we are putting effort to support version ES6 instead.
