### ISSUE TITLE
some tests depend on other test side effects

### ISSUE THREAD

**Issue by claymccoy** [SumoLogic/elasticsearch-client#93]
It is surprising when your passing test starts to fail when run with all tests in the file.
In RestlasticSearchClientTest the tests share state in ES and are isolated by the use of PhrasePrefixQuery on a field. It is not obvious when first working in the file.
A typical way of isolating test data in a database is to clear the data in some way before each new test run. I tried using OneInstancePerTest which would provide a clean ES for each test, but it caused a few tests to fail. Those tests can't be run on their own either. It appears that they depend the side effects of other tests to pass.
It seems worthwhile to make writing tests as easy as possible with few surprises in order to encourage outside contributors to write tests.

**Comment by rcoh** [comment]
Absolutely! I also had assumed I had set up the tests to be independent and I wrote most of them ;-)

I will try to make the change to OneInstancePerTest soon
