### ISSUE TITLE
Basic authentication over https

### ISSUE THREAD

**Issue by z4f1r0v** [SumoLogic/elasticsearch-client#98]
Can you please explain to me how I could achieve something as simple as `https://<username>:<password>@<host>:<port>` with this client? Is that even possible?

I've found that `runRawEsRequest` is worth a shot but the `buildUri` that it uses underneath is not ready to accept `<username>` and `<password>`.

Thanks!

**Comment by rcoh** [comment]
I think you can write your own request signer that injects the necessary headers
